[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.0-beta.2"

[[constraint]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.12.0-beta.2"

[prune]
  go-tests = true
  unused-packages = true
