[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.1"

[[constraint]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.12.1"

[prune]
  go-tests = true
  unused-packages = true
