[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.1"

[[constraint]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.12.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.0"

[prune]
  go-tests = true
  unused-packages = true
