apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-metrics-prom
  name: kube-metrics-prom
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-metrics-prom
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-metrics-prom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-metrics-prom
subjects:
- kind: ServiceAccount
  name: kube-metrics-prom
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-metrics-prom
  labels:
    app: kube-metrics-prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-metrics-prom
  template:
    metadata:
      labels:
        app: kube-metrics-prom
    spec:
      containers:
      - name: kube-metrics-prom
        image: quay.io/bmcstdio/kube-metrics-prom:v0.1.0
        args:
        - kube-metrics-prom
        ports:
        - name: http
          containerPort: 9100
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
      serviceAccountName: kube-metrics-prom
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-metrics-prom
  name: kube-metrics-prom
spec:
  ports:
    - port: 9100
      targetPort: 9100
  selector:
    app: kube-metrics-prom
